### ISSUE TITLE
Load input configuration into a model

### ISSUE THREAD

**Issue by rmc3** [stelligent/cumulogenesis#1]
Input configuration should be loaded into an organization model that represents the desired state of an AWS organization. A suggested YAML input configuration format is below.

```
---
root: '123456789' # the account id; used by orgroller to verify the Org root
featureset: 'ALL' # use this organization for centralized management instead of just centralized billing
version: '0.1'
provisioner:
  role: org-bootstrapper # the role name generated in new member accounts used for resource provisioning 
  type: cfn-stack-set # if resource stacks are described, use AWS Stack-Sets to provision them

accounts: # list of member accounts to create or invite
  - name: foo-account # the member account's name
    owner: foo-owner-email@mycompany.com # the email address used to activate the member account 
    groups:
      - foo-bar-group # arbitrary grouping mechanism for resource provisioning
  - name: bar-account
    owner: bar-owner-email@othercompany.com
    groups:
      - foo-bar-group
  - name: pre-existing-account
    owner: that-account-email@thatcompany.com
    invitation:
      accountid: '987654321'

policies: # list of service control policies to create
  - name: no-x-policy
    description: allows all services to be utilized except <X>
    document: 
      location: # if provided, a URI for the policy document
      content: # if provided, inline YAML-based service control policy document content
  - name: scp-federation-only
    description: enables only those services required for IDP federation
    document:
      location: # URI of the policy document

orgunits: # list of top-level Organizational Units; nested structure represents hierarchy
  - name: IAM Federation
    policies: # list of policies to apply, cross-referenced by policy.name
      - scp-federation-only
    accounts: # list of accounts to place into this OU, cross-referenced by account.name
      - pre-existing-account
    orgunits: [] # list of organizational units under this OU
  - name: The Foos
    policies: 
      - no-x-policy
    accounts:
      - foo-account
    orgunits: 
      - name: The Bars
        policies: []
        accounts:
          - bar-account
        orgunits: []

stacks: # list of resource stacks to create
  - name: core-vpc
    groups: [] # list of groups whose accounts will receive resource stacks in target regions
    accounts: [] # list of accounts to receive resource stacks in target regions
    orgunits: # list of orgunits whose descendent accounts will receive resource stacks in target regions 
      - name: The Foos
        regions:
          - us-east-1
          - us-east-2
    template:
      location: # if provided, a URI for the template document
      content: # if provided, inline string content for the template
  - name: federation-idp
    groups: []
    accounts:
      - name: pre-existing-account
        regions:
          - us-east-1
    orgunits: []
```
